#/tracking/verbose 1
/run/initialize

/gps/pos/type Volume
/gps/pos/shape Cylinder

/gps/pos/centre 0 0 0
/gps/pos/radius 95 mm
/gps/pos/halfz 465 mm
/gps/pos/rot1 1 0 0
/gps/pos/rot2 0 0 1

/gps/pos/confine physFuel
/gps/ang/type iso
/gps/source/intensity 1

/gps/particle neutron
#/gps/pos/type Point
#/gps/pos/centre 0 0 -21 cm
#/gps/source/intensity 1
#/gps/direction 0 0 1
/gps/ene/mono 0.5 MeV

#use line below to set file name
#allows change between runs via macro alleviating need to rename later
#NOTE: no need to add ".root" as default file type is root. You may be able 
#to name files with .csv but not sure if this will cause errors due to 
#Ntuple data structure.

/analysis/setFileName 1MHalfMeVmonoDistributedNeutronsDeposited
/run/beamOn 1000000
